//
// File generated by /usr/local/root_v5.32_binary_m64//bin/rootcint at Tue Mar 25 21:18:11 2014

// Do NOT change. Changes will be lost next time file is generated
//

#define R__DICTIONARY_FILENAME dictVec2d
#include "RConfig.h" //rootcint 4834
#if !defined(R__ACCESS_IN_SYMBOL)
//Break the privacy of classes -- Disabled for the moment
#define private public
#define protected public
#endif

// Since CINT ignores the std namespace, we need to do so in this file.
namespace std {} using namespace std;
#include "dictVec2d.h"

#include "TClass.h"
#include "TBuffer.h"
#include "TMemberInspector.h"
#include "TError.h"

#ifndef G__ROOT
#define G__ROOT
#endif

#include "RtypesImp.h"
#include "TIsAProxy.h"
#include "TFileMergeInfo.h"

// START OF SHADOWS

namespace ROOT {
   namespace Shadow {
   } // of namespace Shadow
} // of namespace ROOT
// END OF SHADOWS

namespace ROOT {
   void vec2d_ShowMembers(void *obj, TMemberInspector &R__insp);
   static void *new_vec2d(void *p = 0);
   static void *newArray_vec2d(Long_t size, void *p);
   static void delete_vec2d(void *p);
   static void deleteArray_vec2d(void *p);
   static void destruct_vec2d(void *p);
   static void streamer_vec2d(TBuffer &buf, void *obj);

   // Function generating the singleton type initializer
   static TGenericClassInfo *GenerateInitInstanceLocal(const ::vec2d*)
   {
      ::vec2d *ptr = 0;
      static ::TVirtualIsAProxy* isa_proxy = new ::TInstrumentedIsAProxy< ::vec2d >(0);
      static ::ROOT::TGenericClassInfo 
         instance("vec2d", ::vec2d::Class_Version(), "./vec2d.h", 12,
                  typeid(::vec2d), DefineBehavior(ptr, ptr),
                  &::vec2d::Dictionary, isa_proxy, 0,
                  sizeof(::vec2d) );
      instance.SetNew(&new_vec2d);
      instance.SetNewArray(&newArray_vec2d);
      instance.SetDelete(&delete_vec2d);
      instance.SetDeleteArray(&deleteArray_vec2d);
      instance.SetDestructor(&destruct_vec2d);
      instance.SetStreamerFunc(&streamer_vec2d);
      return &instance;
   }
   TGenericClassInfo *GenerateInitInstance(const ::vec2d*)
   {
      return GenerateInitInstanceLocal((::vec2d*)0);
   }
   // Static variable to force the class initialization
   static ::ROOT::TGenericClassInfo *_R__UNIQUE_(Init) = GenerateInitInstanceLocal((const ::vec2d*)0x0); R__UseDummy(_R__UNIQUE_(Init));
} // end of namespace ROOT

//______________________________________________________________________________
TClass *vec2d::fgIsA = 0;  // static to hold class pointer

//______________________________________________________________________________
const char *vec2d::Class_Name()
{
   return "vec2d";
}

//______________________________________________________________________________
const char *vec2d::ImplFileName()
{
   return ::ROOT::GenerateInitInstanceLocal((const ::vec2d*)0x0)->GetImplFileName();
}

//______________________________________________________________________________
int vec2d::ImplFileLine()
{
   return ::ROOT::GenerateInitInstanceLocal((const ::vec2d*)0x0)->GetImplFileLine();
}

//______________________________________________________________________________
void vec2d::Dictionary()
{
   fgIsA = ::ROOT::GenerateInitInstanceLocal((const ::vec2d*)0x0)->GetClass();
}

//______________________________________________________________________________
TClass *vec2d::Class()
{
   if (!fgIsA) fgIsA = ::ROOT::GenerateInitInstanceLocal((const ::vec2d*)0x0)->GetClass();
   return fgIsA;
}

//______________________________________________________________________________
void vec2d::Streamer(TBuffer &R__b)
{
   // Stream an object of class vec2d.

   UInt_t R__s, R__c;
   if (R__b.IsReading()) {
      Version_t R__v = R__b.ReadVersion(&R__s, &R__c); if (R__v) { }
      TObject::Streamer(R__b);
      R__b >> x;
      R__b >> y;
      R__b.CheckByteCount(R__s, R__c, vec2d::IsA());
   } else {
      R__c = R__b.WriteVersion(vec2d::IsA(), kTRUE);
      TObject::Streamer(R__b);
      R__b << x;
      R__b << y;
      R__b.SetByteCount(R__c, kTRUE);
   }
}

//______________________________________________________________________________
void vec2d::ShowMembers(TMemberInspector &R__insp)
{
      // Inspect the data members of an object of class vec2d.
      TClass *R__cl = ::vec2d::IsA();
      if (R__cl || R__insp.IsA()) { }
      R__insp.Inspect(R__cl, R__insp.GetParent(), "x", &x);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "y", &y);
      TObject::ShowMembers(R__insp);
}

namespace ROOT {
   // Wrappers around operator new
   static void *new_vec2d(void *p) {
      return  p ? new(p) ::vec2d : new ::vec2d;
   }
   static void *newArray_vec2d(Long_t nElements, void *p) {
      return p ? new(p) ::vec2d[nElements] : new ::vec2d[nElements];
   }
   // Wrapper around operator delete
   static void delete_vec2d(void *p) {
      delete ((::vec2d*)p);
   }
   static void deleteArray_vec2d(void *p) {
      delete [] ((::vec2d*)p);
   }
   static void destruct_vec2d(void *p) {
      typedef ::vec2d current_t;
      ((current_t*)p)->~current_t();
   }
   // Wrapper around a custom streamer member function.
   static void streamer_vec2d(TBuffer &buf, void *obj) {
      ((::vec2d*)obj)->::vec2d::Streamer(buf);
   }
} // end of namespace ROOT for class ::vec2d

/********************************************************
* dictVec2d.C
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************/

#ifdef G__MEMTEST
#undef malloc
#undef free
#endif

#if defined(__GNUC__) && __GNUC__ >= 4 && ((__GNUC_MINOR__ == 2 && __GNUC_PATCHLEVEL__ >= 1) || (__GNUC_MINOR__ >= 3))
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif

extern "C" void G__cpp_reset_tagtabledictVec2d();

extern "C" void G__set_cpp_environmentdictVec2d() {
  G__add_compiledheader("TObject.h");
  G__add_compiledheader("TMemberInspector.h");
  G__add_compiledheader("vec2d.h");
  G__cpp_reset_tagtabledictVec2d();
}
#include <new>
extern "C" int G__cpp_dllrevdictVec2d() { return(30051515); }

/*********************************************************
* Member function Interface Method
*********************************************************/

/* vec2d */
static int G__dictVec2d_162_0_1(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   vec2d* p = NULL;
   char* gvp = (char*) G__getgvp();
   int n = G__getaryconstruct();
   if (n) {
     if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
       p = new vec2d[n];
     } else {
       p = new((void*) gvp) vec2d[n];
     }
   } else {
     if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
       p = new vec2d;
     } else {
       p = new((void*) gvp) vec2d;
     }
   }
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__dictVec2dLN_vec2d));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__dictVec2d_162_0_2(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   vec2d* p = NULL;
   char* gvp = (char*) G__getgvp();
   //m: 2
   if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
     p = new vec2d((double) G__double(libp->para[0]), (double) G__double(libp->para[1]));
   } else {
     p = new((void*) gvp) vec2d((double) G__double(libp->para[0]), (double) G__double(libp->para[1]));
   }
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__dictVec2dLN_vec2d));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__dictVec2d_162_0_3(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      {
         vec2d* pobj;
         vec2d xobj = ((vec2d*) G__getstructoffset())->operator+=(*(vec2d*) libp->para[0].ref);
         pobj = new vec2d(xobj);
         result7->obj.i = (long) ((void*) pobj);
         result7->ref = result7->obj.i;
         G__store_tempobject(*result7);
      }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__dictVec2d_162_0_4(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      {
         vec2d* pobj;
         vec2d xobj = ((vec2d*) G__getstructoffset())->operator+(*(vec2d*) libp->para[0].ref);
         pobj = new vec2d(xobj);
         result7->obj.i = (long) ((void*) pobj);
         result7->ref = result7->obj.i;
         G__store_tempobject(*result7);
      }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__dictVec2d_162_0_5(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((vec2d*) G__getstructoffset())->SetX((double) G__double(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__dictVec2d_162_0_6(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((vec2d*) G__getstructoffset())->SetY((double) G__double(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__dictVec2d_162_0_7(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 100, (double) ((vec2d*) G__getstructoffset())->GetX());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__dictVec2d_162_0_8(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 100, (double) ((vec2d*) G__getstructoffset())->GetY());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__dictVec2d_162_0_9(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((vec2d*) G__getstructoffset())->Print();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__dictVec2d_162_0_10(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 100, (double) ((vec2d*) G__getstructoffset())->Length());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__dictVec2d_162_0_11(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 85, (long) vec2d::Class());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__dictVec2d_162_0_12(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) vec2d::Class_Name());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__dictVec2d_162_0_13(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 115, (long) vec2d::Class_Version());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__dictVec2d_162_0_14(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      vec2d::Dictionary();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__dictVec2d_162_0_18(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((vec2d*) G__getstructoffset())->StreamerNVirtual(*(TBuffer*) libp->para[0].ref);
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__dictVec2d_162_0_19(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) vec2d::DeclFileName());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__dictVec2d_162_0_20(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) vec2d::ImplFileLine());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__dictVec2d_162_0_21(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) vec2d::ImplFileName());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__dictVec2d_162_0_22(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) vec2d::DeclFileLine());
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic copy constructor
static int G__dictVec2d_162_0_23(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)

{
   vec2d* p;
   void* tmp = (void*) G__int(libp->para[0]);
   p = new vec2d(*(vec2d*) tmp);
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__dictVec2dLN_vec2d));
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic destructor
typedef vec2d G__Tvec2d;
static int G__dictVec2d_162_0_24(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   char* gvp = (char*) G__getgvp();
   long soff = G__getstructoffset();
   int n = G__getaryconstruct();
   //
   //has_a_delete: 1
   //has_own_delete1arg: 0
   //has_own_delete2arg: 0
   //
   if (!soff) {
     return(1);
   }
   if (n) {
     if (gvp == (char*)G__PVOID) {
       delete[] (vec2d*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       for (int i = n - 1; i >= 0; --i) {
         ((vec2d*) (soff+(sizeof(vec2d)*i)))->~G__Tvec2d();
       }
       G__setgvp((long)gvp);
     }
   } else {
     if (gvp == (char*)G__PVOID) {
       delete (vec2d*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       ((vec2d*) (soff))->~G__Tvec2d();
       G__setgvp((long)gvp);
     }
   }
   G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic assignment operator
static int G__dictVec2d_162_0_25(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   vec2d* dest = (vec2d*) G__getstructoffset();
   *dest = *(vec2d*) libp->para[0].ref;
   const vec2d& obj = *dest;
   result7->ref = (long) (&obj);
   result7->obj.i = (long) (&obj);
   return(1 || funcname || hash || result7 || libp) ;
}


/* Setting up global function */

/*********************************************************
* Member function Stub
*********************************************************/

/* vec2d */

/*********************************************************
* Global function Stub
*********************************************************/

/*********************************************************
* Get size of pointer to member function
*********************************************************/
class G__Sizep2memfuncdictVec2d {
 public:
  G__Sizep2memfuncdictVec2d(): p(&G__Sizep2memfuncdictVec2d::sizep2memfunc) {}
    size_t sizep2memfunc() { return(sizeof(p)); }
  private:
    size_t (G__Sizep2memfuncdictVec2d::*p)();
};

size_t G__get_sizep2memfuncdictVec2d()
{
  G__Sizep2memfuncdictVec2d a;
  G__setsizep2memfunc((int)a.sizep2memfunc());
  return((size_t)a.sizep2memfunc());
}


/*********************************************************
* virtual base class offset calculation interface
*********************************************************/

   /* Setting up class inheritance */

/*********************************************************
* Inheritance information setup/
*********************************************************/
extern "C" void G__cpp_setup_inheritancedictVec2d() {

   /* Setting up class inheritance */
   if(0==G__getnumbaseclass(G__get_linked_tagnum(&G__dictVec2dLN_vec2d))) {
     vec2d *G__Lderived;
     G__Lderived=(vec2d*)0x1000;
     {
       TObject *G__Lpbase=(TObject*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__dictVec2dLN_vec2d),G__get_linked_tagnum(&G__dictVec2dLN_TObject),(long)G__Lpbase-(long)G__Lderived,1,1);
     }
   }
}

/*********************************************************
* typedef information setup/
*********************************************************/
extern "C" void G__cpp_setup_typetabledictVec2d() {

   /* Setting up typedef entry */
   G__search_typename2("Version_t",115,-1,0,-1);
   G__setnewtype(-1,"Class version identifier (short)",0);
   G__search_typename2("vector<ROOT::TSchemaHelper>",117,G__get_linked_tagnum(&G__dictVec2dLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__dictVec2dLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__dictVec2dLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__dictVec2dLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__dictVec2dLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<TVirtualArray*>",117,G__get_linked_tagnum(&G__dictVec2dLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__dictVec2dLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__dictVec2dLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__dictVec2dLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__dictVec2dLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR));
   G__setnewtype(-1,NULL,0);
}

/*********************************************************
* Data Member information setup/
*********************************************************/

   /* Setting up class,struct,union tag member variable */

   /* vec2d */
static void G__setup_memvarvec2d(void) {
   G__tag_memvar_setup(G__get_linked_tagnum(&G__dictVec2dLN_vec2d));
   { vec2d *p; p=(vec2d*)0x1000; if (p) { }
   G__memvar_setup((void*)0,100,0,0,-1,-1,-1,2,"x=",0,(char*)NULL);
   G__memvar_setup((void*)0,100,0,0,-1,-1,-1,2,"y=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__dictVec2dLN_TClass),-1,-2,4,"fgIsA=",0,(char*)NULL);
   }
   G__tag_memvar_reset();
}

extern "C" void G__cpp_setup_memvardictVec2d() {
}
/***********************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
***********************************************************/

/*********************************************************
* Member function information setup for each class
*********************************************************/
static void G__setup_memfuncvec2d(void) {
   /* vec2d */
   G__tag_memfunc_setup(G__get_linked_tagnum(&G__dictVec2dLN_vec2d));
   G__memfunc_setup("vec2d",468,G__dictVec2d_162_0_1, 105, G__get_linked_tagnum(&G__dictVec2dLN_vec2d), -1, 0, 0, 1, 1, 0, "", "default", (void*) NULL, 0);
   G__memfunc_setup("vec2d",468,G__dictVec2d_162_0_2, 105, G__get_linked_tagnum(&G__dictVec2dLN_vec2d), -1, 0, 2, 1, 1, 0, 
"d - - 0 - mx d - - 0 - my", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("operator+=",980,G__dictVec2d_162_0_3, 117, G__get_linked_tagnum(&G__dictVec2dLN_vec2d), -1, 0, 1, 1, 1, 0, "u 'vec2d' - 1 - -", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("operator+",919,G__dictVec2d_162_0_4, 117, G__get_linked_tagnum(&G__dictVec2dLN_vec2d), -1, 0, 1, 1, 1, 0, "u 'vec2d' - 1 - -", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("SetX",388,G__dictVec2d_162_0_5, 121, -1, -1, 0, 1, 1, 1, 0, "d - - 0 - mx", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("SetY",389,G__dictVec2d_162_0_6, 121, -1, -1, 0, 1, 1, 1, 0, "d - - 0 - my", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetX",376,G__dictVec2d_162_0_7, 100, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetY",377,G__dictVec2d_162_0_8, 100, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Print",525,G__dictVec2d_162_0_9, 121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Length",610,G__dictVec2d_162_0_10, 100, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Class",502,G__dictVec2d_162_0_11, 85, G__get_linked_tagnum(&G__dictVec2dLN_TClass), -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (TClass* (*)())(&vec2d::Class) ), 0);
   G__memfunc_setup("Class_Name",982,G__dictVec2d_162_0_12, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&vec2d::Class_Name) ), 0);
   G__memfunc_setup("Class_Version",1339,G__dictVec2d_162_0_13, 115, -1, G__defined_typename("Version_t"), 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (Version_t (*)())(&vec2d::Class_Version) ), 0);
   G__memfunc_setup("Dictionary",1046,G__dictVec2d_162_0_14, 121, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (void (*)())(&vec2d::Dictionary) ), 0);
   G__memfunc_setup("IsA",253,(G__InterfaceMethod) NULL,85, G__get_linked_tagnum(&G__dictVec2dLN_TClass), -1, 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("ShowMembers",1132,(G__InterfaceMethod) NULL,121, -1, -1, 0, 1, 1, 1, 0, "u 'TMemberInspector' - 1 - insp", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("Streamer",835,(G__InterfaceMethod) NULL,121, -1, -1, 0, 1, 1, 1, 0, "u 'TBuffer' - 1 - b", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("StreamerNVirtual",1656,G__dictVec2d_162_0_18, 121, -1, -1, 0, 1, 1, 1, 0, "u 'TBuffer' - 1 - b", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("DeclFileName",1145,G__dictVec2d_162_0_19, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&vec2d::DeclFileName) ), 0);
   G__memfunc_setup("ImplFileLine",1178,G__dictVec2d_162_0_20, 105, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (int (*)())(&vec2d::ImplFileLine) ), 0);
   G__memfunc_setup("ImplFileName",1171,G__dictVec2d_162_0_21, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&vec2d::ImplFileName) ), 0);
   G__memfunc_setup("DeclFileLine",1152,G__dictVec2d_162_0_22, 105, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (int (*)())(&vec2d::DeclFileLine) ), 0);
   // automatic copy constructor
   G__memfunc_setup("vec2d", 468, G__dictVec2d_162_0_23, (int) ('i'), G__get_linked_tagnum(&G__dictVec2dLN_vec2d), -1, 0, 1, 1, 1, 0, "u 'vec2d' - 11 - -", (char*) NULL, (void*) NULL, 0);
   // automatic destructor
   G__memfunc_setup("~vec2d", 594, G__dictVec2d_162_0_24, (int) ('y'), -1, -1, 0, 0, 1, 1, 0, "", (char*) NULL, (void*) NULL, 1);
   // automatic assignment operator
   G__memfunc_setup("operator=", 937, G__dictVec2d_162_0_25, (int) ('u'), G__get_linked_tagnum(&G__dictVec2dLN_vec2d), -1, 1, 1, 1, 1, 0, "u 'vec2d' - 11 - -", (char*) NULL, (void*) NULL, 0);
   G__tag_memfunc_reset();
}


/*********************************************************
* Member function information setup
*********************************************************/
extern "C" void G__cpp_setup_memfuncdictVec2d() {
}

/*********************************************************
* Global variable information setup for each class
*********************************************************/
static void G__cpp_setup_global0() {

   /* Setting up global variables */
   G__resetplocal();

}

static void G__cpp_setup_global1() {
}

static void G__cpp_setup_global2() {

   G__resetglobalenv();
}
extern "C" void G__cpp_setup_globaldictVec2d() {
  G__cpp_setup_global0();
  G__cpp_setup_global1();
  G__cpp_setup_global2();
}

/*********************************************************
* Global function information setup for each class
*********************************************************/
static void G__cpp_setup_func0() {
   G__lastifuncposition();

}

static void G__cpp_setup_func1() {
}

static void G__cpp_setup_func2() {
}

static void G__cpp_setup_func3() {
}

static void G__cpp_setup_func4() {
}

static void G__cpp_setup_func5() {
}

static void G__cpp_setup_func6() {
}

static void G__cpp_setup_func7() {
}

static void G__cpp_setup_func8() {
}

static void G__cpp_setup_func9() {
}

static void G__cpp_setup_func10() {
}

static void G__cpp_setup_func11() {
}

static void G__cpp_setup_func12() {

   G__resetifuncposition();
}

extern "C" void G__cpp_setup_funcdictVec2d() {
  G__cpp_setup_func0();
  G__cpp_setup_func1();
  G__cpp_setup_func2();
  G__cpp_setup_func3();
  G__cpp_setup_func4();
  G__cpp_setup_func5();
  G__cpp_setup_func6();
  G__cpp_setup_func7();
  G__cpp_setup_func8();
  G__cpp_setup_func9();
  G__cpp_setup_func10();
  G__cpp_setup_func11();
  G__cpp_setup_func12();
}

/*********************************************************
* Class,struct,union,enum tag information setup
*********************************************************/
/* Setup class/struct taginfo */
G__linked_taginfo G__dictVec2dLN_TClass = { "TClass" , 99 , -1 };
G__linked_taginfo G__dictVec2dLN_TBuffer = { "TBuffer" , 99 , -1 };
G__linked_taginfo G__dictVec2dLN_TMemberInspector = { "TMemberInspector" , 99 , -1 };
G__linked_taginfo G__dictVec2dLN_TObject = { "TObject" , 99 , -1 };
G__linked_taginfo G__dictVec2dLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR = { "vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >" , 99 , -1 };
G__linked_taginfo G__dictVec2dLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR = { "reverse_iterator<vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >::iterator>" , 99 , -1 };
G__linked_taginfo G__dictVec2dLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR = { "vector<TVirtualArray*,allocator<TVirtualArray*> >" , 99 , -1 };
G__linked_taginfo G__dictVec2dLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<TVirtualArray*,allocator<TVirtualArray*> >::iterator>" , 99 , -1 };
G__linked_taginfo G__dictVec2dLN_vec2d = { "vec2d" , 99 , -1 };

/* Reset class/struct taginfo */
extern "C" void G__cpp_reset_tagtabledictVec2d() {
  G__dictVec2dLN_TClass.tagnum = -1 ;
  G__dictVec2dLN_TBuffer.tagnum = -1 ;
  G__dictVec2dLN_TMemberInspector.tagnum = -1 ;
  G__dictVec2dLN_TObject.tagnum = -1 ;
  G__dictVec2dLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR.tagnum = -1 ;
  G__dictVec2dLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__dictVec2dLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR.tagnum = -1 ;
  G__dictVec2dLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__dictVec2dLN_vec2d.tagnum = -1 ;
}


extern "C" void G__cpp_setup_tagtabledictVec2d() {

   /* Setting up class,struct,union tag entry */
   G__get_linked_tagnum_fwd(&G__dictVec2dLN_TClass);
   G__get_linked_tagnum_fwd(&G__dictVec2dLN_TBuffer);
   G__get_linked_tagnum_fwd(&G__dictVec2dLN_TMemberInspector);
   G__get_linked_tagnum_fwd(&G__dictVec2dLN_TObject);
   G__get_linked_tagnum_fwd(&G__dictVec2dLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR);
   G__get_linked_tagnum_fwd(&G__dictVec2dLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__dictVec2dLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR);
   G__get_linked_tagnum_fwd(&G__dictVec2dLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR);
   G__tagtable_setup(G__get_linked_tagnum_fwd(&G__dictVec2dLN_vec2d),sizeof(vec2d),-1,62720,(char*)NULL,G__setup_memvarvec2d,G__setup_memfuncvec2d);
}
extern "C" void G__cpp_setupdictVec2d(void) {
  G__check_setup_version(30051515,"G__cpp_setupdictVec2d()");
  G__set_cpp_environmentdictVec2d();
  G__cpp_setup_tagtabledictVec2d();

  G__cpp_setup_inheritancedictVec2d();

  G__cpp_setup_typetabledictVec2d();

  G__cpp_setup_memvardictVec2d();

  G__cpp_setup_memfuncdictVec2d();
  G__cpp_setup_globaldictVec2d();
  G__cpp_setup_funcdictVec2d();

   if(0==G__getsizep2memfunc()) G__get_sizep2memfuncdictVec2d();
  return;
}
class G__cpp_setup_initdictVec2d {
  public:
    G__cpp_setup_initdictVec2d() { G__add_setup_func("dictVec2d",(G__incsetup)(&G__cpp_setupdictVec2d)); G__call_setup_funcs(); }
   ~G__cpp_setup_initdictVec2d() { G__remove_setup_func("dictVec2d"); }
};
G__cpp_setup_initdictVec2d G__cpp_setup_initializerdictVec2d;

