/********************************************************************
* dictVec2d.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error dictVec2d.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtabledictVec2d();
extern void G__cpp_setup_inheritancedictVec2d();
extern void G__cpp_setup_typetabledictVec2d();
extern void G__cpp_setup_memvardictVec2d();
extern void G__cpp_setup_globaldictVec2d();
extern void G__cpp_setup_memfuncdictVec2d();
extern void G__cpp_setup_funcdictVec2d();
extern void G__set_cpp_environmentdictVec2d();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "vec2d.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__dictVec2dLN_TClass;
extern G__linked_taginfo G__dictVec2dLN_TBuffer;
extern G__linked_taginfo G__dictVec2dLN_TMemberInspector;
extern G__linked_taginfo G__dictVec2dLN_TObject;
extern G__linked_taginfo G__dictVec2dLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__dictVec2dLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__dictVec2dLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__dictVec2dLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__dictVec2dLN_vec2d;

/* STUB derived class for protected member access */
