/********************************************************************
* dictEvent.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error dictEvent.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtabledictEvent();
extern void G__cpp_setup_inheritancedictEvent();
extern void G__cpp_setup_typetabledictEvent();
extern void G__cpp_setup_memvardictEvent();
extern void G__cpp_setup_globaldictEvent();
extern void G__cpp_setup_memfuncdictEvent();
extern void G__cpp_setup_funcdictEvent();
extern void G__set_cpp_environmentdictEvent();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "vec2d.h"
#include "event.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__dictEventLN_TClass;
extern G__linked_taginfo G__dictEventLN_TBuffer;
extern G__linked_taginfo G__dictEventLN_TMemberInspector;
extern G__linked_taginfo G__dictEventLN_TObject;
extern G__linked_taginfo G__dictEventLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__dictEventLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__dictEventLN_TObjArray;
extern G__linked_taginfo G__dictEventLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__dictEventLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__dictEventLN_vec2d;
extern G__linked_taginfo G__dictEventLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR;
extern G__linked_taginfo G__dictEventLN_event;

/* STUB derived class for protected member access */
