//
// File generated by /usr/local/root_v5.32_binary_m64//bin/rootcint at Sat Mar 29 16:03:50 2014

// Do NOT change. Changes will be lost next time file is generated
//

#define R__DICTIONARY_FILENAME dictEvent
#include "RConfig.h" //rootcint 4834
#if !defined(R__ACCESS_IN_SYMBOL)
//Break the privacy of classes -- Disabled for the moment
#define private public
#define protected public
#endif

// Since CINT ignores the std namespace, we need to do so in this file.
namespace std {} using namespace std;
#include "dictEvent.h"

#include "TClass.h"
#include "TBuffer.h"
#include "TMemberInspector.h"
#include "TError.h"

#ifndef G__ROOT
#define G__ROOT
#endif

#include "RtypesImp.h"
#include "TIsAProxy.h"
#include "TFileMergeInfo.h"

// START OF SHADOWS

namespace ROOT {
   namespace Shadow {
   } // of namespace Shadow
} // of namespace ROOT
// END OF SHADOWS

namespace ROOT {
   void vec2d_ShowMembers(void *obj, TMemberInspector &R__insp);
   static void *new_vec2d(void *p = 0);
   static void *newArray_vec2d(Long_t size, void *p);
   static void delete_vec2d(void *p);
   static void deleteArray_vec2d(void *p);
   static void destruct_vec2d(void *p);
   static void streamer_vec2d(TBuffer &buf, void *obj);

   // Function generating the singleton type initializer
   static TGenericClassInfo *GenerateInitInstanceLocal(const ::vec2d*)
   {
      ::vec2d *ptr = 0;
      static ::TVirtualIsAProxy* isa_proxy = new ::TInstrumentedIsAProxy< ::vec2d >(0);
      static ::ROOT::TGenericClassInfo 
         instance("vec2d", ::vec2d::Class_Version(), "./vec2d.h", 13,
                  typeid(::vec2d), DefineBehavior(ptr, ptr),
                  &::vec2d::Dictionary, isa_proxy, 0,
                  sizeof(::vec2d) );
      instance.SetNew(&new_vec2d);
      instance.SetNewArray(&newArray_vec2d);
      instance.SetDelete(&delete_vec2d);
      instance.SetDeleteArray(&deleteArray_vec2d);
      instance.SetDestructor(&destruct_vec2d);
      instance.SetStreamerFunc(&streamer_vec2d);
      return &instance;
   }
   TGenericClassInfo *GenerateInitInstance(const ::vec2d*)
   {
      return GenerateInitInstanceLocal((::vec2d*)0);
   }
   // Static variable to force the class initialization
   static ::ROOT::TGenericClassInfo *_R__UNIQUE_(Init) = GenerateInitInstanceLocal((const ::vec2d*)0x0); R__UseDummy(_R__UNIQUE_(Init));
} // end of namespace ROOT

namespace ROOT {
   void event_ShowMembers(void *obj, TMemberInspector &R__insp);
   static void *new_event(void *p = 0);
   static void *newArray_event(Long_t size, void *p);
   static void delete_event(void *p);
   static void deleteArray_event(void *p);
   static void destruct_event(void *p);
   static void streamer_event(TBuffer &buf, void *obj);

   // Function generating the singleton type initializer
   static TGenericClassInfo *GenerateInitInstanceLocal(const ::event*)
   {
      ::event *ptr = 0;
      static ::TVirtualIsAProxy* isa_proxy = new ::TInstrumentedIsAProxy< ::event >(0);
      static ::ROOT::TGenericClassInfo 
         instance("event", ::event::Class_Version(), "./event.h", 15,
                  typeid(::event), DefineBehavior(ptr, ptr),
                  &::event::Dictionary, isa_proxy, 0,
                  sizeof(::event) );
      instance.SetNew(&new_event);
      instance.SetNewArray(&newArray_event);
      instance.SetDelete(&delete_event);
      instance.SetDeleteArray(&deleteArray_event);
      instance.SetDestructor(&destruct_event);
      instance.SetStreamerFunc(&streamer_event);
      return &instance;
   }
   TGenericClassInfo *GenerateInitInstance(const ::event*)
   {
      return GenerateInitInstanceLocal((::event*)0);
   }
   // Static variable to force the class initialization
   static ::ROOT::TGenericClassInfo *_R__UNIQUE_(Init) = GenerateInitInstanceLocal((const ::event*)0x0); R__UseDummy(_R__UNIQUE_(Init));
} // end of namespace ROOT

//______________________________________________________________________________
TClass *vec2d::fgIsA = 0;  // static to hold class pointer

//______________________________________________________________________________
const char *vec2d::Class_Name()
{
   return "vec2d";
}

//______________________________________________________________________________
const char *vec2d::ImplFileName()
{
   return ::ROOT::GenerateInitInstanceLocal((const ::vec2d*)0x0)->GetImplFileName();
}

//______________________________________________________________________________
int vec2d::ImplFileLine()
{
   return ::ROOT::GenerateInitInstanceLocal((const ::vec2d*)0x0)->GetImplFileLine();
}

//______________________________________________________________________________
void vec2d::Dictionary()
{
   fgIsA = ::ROOT::GenerateInitInstanceLocal((const ::vec2d*)0x0)->GetClass();
}

//______________________________________________________________________________
TClass *vec2d::Class()
{
   if (!fgIsA) fgIsA = ::ROOT::GenerateInitInstanceLocal((const ::vec2d*)0x0)->GetClass();
   return fgIsA;
}

//______________________________________________________________________________
TClass *event::fgIsA = 0;  // static to hold class pointer

//______________________________________________________________________________
const char *event::Class_Name()
{
   return "event";
}

//______________________________________________________________________________
const char *event::ImplFileName()
{
   return ::ROOT::GenerateInitInstanceLocal((const ::event*)0x0)->GetImplFileName();
}

//______________________________________________________________________________
int event::ImplFileLine()
{
   return ::ROOT::GenerateInitInstanceLocal((const ::event*)0x0)->GetImplFileLine();
}

//______________________________________________________________________________
void event::Dictionary()
{
   fgIsA = ::ROOT::GenerateInitInstanceLocal((const ::event*)0x0)->GetClass();
}

//______________________________________________________________________________
TClass *event::Class()
{
   if (!fgIsA) fgIsA = ::ROOT::GenerateInitInstanceLocal((const ::event*)0x0)->GetClass();
   return fgIsA;
}

//______________________________________________________________________________
void vec2d::Streamer(TBuffer &R__b)
{
   // Stream an object of class vec2d.

   UInt_t R__s, R__c;
   if (R__b.IsReading()) {
      Version_t R__v = R__b.ReadVersion(&R__s, &R__c); if (R__v) { }
      TObject::Streamer(R__b);
      R__b >> x;
      R__b >> y;
      R__b.CheckByteCount(R__s, R__c, vec2d::IsA());
   } else {
      R__c = R__b.WriteVersion(vec2d::IsA(), kTRUE);
      TObject::Streamer(R__b);
      R__b << x;
      R__b << y;
      R__b.SetByteCount(R__c, kTRUE);
   }
}

//______________________________________________________________________________
void vec2d::ShowMembers(TMemberInspector &R__insp)
{
      // Inspect the data members of an object of class vec2d.
      TClass *R__cl = ::vec2d::IsA();
      if (R__cl || R__insp.IsA()) { }
      R__insp.Inspect(R__cl, R__insp.GetParent(), "x", &x);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "y", &y);
      TObject::ShowMembers(R__insp);
}

namespace ROOT {
   // Wrappers around operator new
   static void *new_vec2d(void *p) {
      return  p ? new(p) ::vec2d : new ::vec2d;
   }
   static void *newArray_vec2d(Long_t nElements, void *p) {
      return p ? new(p) ::vec2d[nElements] : new ::vec2d[nElements];
   }
   // Wrapper around operator delete
   static void delete_vec2d(void *p) {
      delete ((::vec2d*)p);
   }
   static void deleteArray_vec2d(void *p) {
      delete [] ((::vec2d*)p);
   }
   static void destruct_vec2d(void *p) {
      typedef ::vec2d current_t;
      ((current_t*)p)->~current_t();
   }
   // Wrapper around a custom streamer member function.
   static void streamer_vec2d(TBuffer &buf, void *obj) {
      ((::vec2d*)obj)->::vec2d::Streamer(buf);
   }
} // end of namespace ROOT for class ::vec2d

//______________________________________________________________________________
void event::Streamer(TBuffer &R__b)
{
   // Stream an object of class event.

   UInt_t R__s, R__c;
   if (R__b.IsReading()) {
      Version_t R__v = R__b.ReadVersion(&R__s, &R__c); if (R__v) { }
      TObject::Streamer(R__b);
      R__b >> eventNumber;
      R__b >> vec2dArray;
      R__b.CheckByteCount(R__s, R__c, event::IsA());
   } else {
      R__c = R__b.WriteVersion(event::IsA(), kTRUE);
      TObject::Streamer(R__b);
      R__b << eventNumber;
      R__b << vec2dArray;
      R__b.SetByteCount(R__c, kTRUE);
   }
}

//______________________________________________________________________________
void event::ShowMembers(TMemberInspector &R__insp)
{
      // Inspect the data members of an object of class event.
      TClass *R__cl = ::event::IsA();
      if (R__cl || R__insp.IsA()) { }
      R__insp.Inspect(R__cl, R__insp.GetParent(), "eventNumber", &eventNumber);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*vec2dArray", &vec2dArray);
      TObject::ShowMembers(R__insp);
}

namespace ROOT {
   // Wrappers around operator new
   static void *new_event(void *p) {
      return  p ? new(p) ::event : new ::event;
   }
   static void *newArray_event(Long_t nElements, void *p) {
      return p ? new(p) ::event[nElements] : new ::event[nElements];
   }
   // Wrapper around operator delete
   static void delete_event(void *p) {
      delete ((::event*)p);
   }
   static void deleteArray_event(void *p) {
      delete [] ((::event*)p);
   }
   static void destruct_event(void *p) {
      typedef ::event current_t;
      ((current_t*)p)->~current_t();
   }
   // Wrapper around a custom streamer member function.
   static void streamer_event(TBuffer &buf, void *obj) {
      ((::event*)obj)->::event::Streamer(buf);
   }
} // end of namespace ROOT for class ::event

/********************************************************
* dictEvent.C
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************/

#ifdef G__MEMTEST
#undef malloc
#undef free
#endif

#if defined(__GNUC__) && __GNUC__ >= 4 && ((__GNUC_MINOR__ == 2 && __GNUC_PATCHLEVEL__ >= 1) || (__GNUC_MINOR__ >= 3))
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif

extern "C" void G__cpp_reset_tagtabledictEvent();

extern "C" void G__set_cpp_environmentdictEvent() {
  G__add_compiledheader("TObject.h");
  G__add_compiledheader("TMemberInspector.h");
  G__add_compiledheader("vec2d.h");
  G__add_compiledheader("event.h");
  G__cpp_reset_tagtabledictEvent();
}
#include <new>
extern "C" int G__cpp_dllrevdictEvent() { return(30051515); }

/*********************************************************
* Member function Interface Method
*********************************************************/

/* vec2d */
static int G__dictEvent_162_0_1(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   vec2d* p = NULL;
   char* gvp = (char*) G__getgvp();
   int n = G__getaryconstruct();
   if (n) {
     if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
       p = new vec2d[n];
     } else {
       p = new((void*) gvp) vec2d[n];
     }
   } else {
     if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
       p = new vec2d;
     } else {
       p = new((void*) gvp) vec2d;
     }
   }
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__dictEventLN_vec2d));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__dictEvent_162_0_2(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   vec2d* p = NULL;
   char* gvp = (char*) G__getgvp();
   //m: 2
   if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
     p = new vec2d((double) G__double(libp->para[0]), (double) G__double(libp->para[1]));
   } else {
     p = new((void*) gvp) vec2d((double) G__double(libp->para[0]), (double) G__double(libp->para[1]));
   }
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__dictEventLN_vec2d));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__dictEvent_162_0_3(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      {
         vec2d* pobj;
         vec2d xobj = ((vec2d*) G__getstructoffset())->operator+=(*(vec2d*) libp->para[0].ref);
         pobj = new vec2d(xobj);
         result7->obj.i = (long) ((void*) pobj);
         result7->ref = result7->obj.i;
         G__store_tempobject(*result7);
      }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__dictEvent_162_0_4(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      {
         vec2d* pobj;
         vec2d xobj = ((vec2d*) G__getstructoffset())->operator+(*(vec2d*) libp->para[0].ref);
         pobj = new vec2d(xobj);
         result7->obj.i = (long) ((void*) pobj);
         result7->ref = result7->obj.i;
         G__store_tempobject(*result7);
      }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__dictEvent_162_0_5(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((vec2d*) G__getstructoffset())->SetX((double) G__double(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__dictEvent_162_0_6(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((vec2d*) G__getstructoffset())->SetY((double) G__double(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__dictEvent_162_0_7(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 100, (double) ((vec2d*) G__getstructoffset())->GetX());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__dictEvent_162_0_8(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 100, (double) ((vec2d*) G__getstructoffset())->GetY());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__dictEvent_162_0_9(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((vec2d*) G__getstructoffset())->Print();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__dictEvent_162_0_10(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 100, (double) ((const vec2d*) G__getstructoffset())->Length());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__dictEvent_162_0_13(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 85, (long) vec2d::Class());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__dictEvent_162_0_14(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) vec2d::Class_Name());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__dictEvent_162_0_15(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 115, (long) vec2d::Class_Version());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__dictEvent_162_0_16(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      vec2d::Dictionary();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__dictEvent_162_0_20(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((vec2d*) G__getstructoffset())->StreamerNVirtual(*(TBuffer*) libp->para[0].ref);
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__dictEvent_162_0_21(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) vec2d::DeclFileName());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__dictEvent_162_0_22(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) vec2d::ImplFileLine());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__dictEvent_162_0_23(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) vec2d::ImplFileName());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__dictEvent_162_0_24(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) vec2d::DeclFileLine());
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic copy constructor
static int G__dictEvent_162_0_25(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)

{
   vec2d* p;
   void* tmp = (void*) G__int(libp->para[0]);
   p = new vec2d(*(vec2d*) tmp);
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__dictEventLN_vec2d));
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic destructor
typedef vec2d G__Tvec2d;
static int G__dictEvent_162_0_26(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   char* gvp = (char*) G__getgvp();
   long soff = G__getstructoffset();
   int n = G__getaryconstruct();
   //
   //has_a_delete: 1
   //has_own_delete1arg: 0
   //has_own_delete2arg: 0
   //
   if (!soff) {
     return(1);
   }
   if (n) {
     if (gvp == (char*)G__PVOID) {
       delete[] (vec2d*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       for (int i = n - 1; i >= 0; --i) {
         ((vec2d*) (soff+(sizeof(vec2d)*i)))->~G__Tvec2d();
       }
       G__setgvp((long)gvp);
     }
   } else {
     if (gvp == (char*)G__PVOID) {
       delete (vec2d*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       ((vec2d*) (soff))->~G__Tvec2d();
       G__setgvp((long)gvp);
     }
   }
   G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic assignment operator
static int G__dictEvent_162_0_27(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   vec2d* dest = (vec2d*) G__getstructoffset();
   *dest = *(vec2d*) libp->para[0].ref;
   const vec2d& obj = *dest;
   result7->ref = (long) (&obj);
   result7->obj.i = (long) (&obj);
   return(1 || funcname || hash || result7 || libp) ;
}


/* event */
static int G__dictEvent_185_0_1(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   event* p = NULL;
   char* gvp = (char*) G__getgvp();
   int n = G__getaryconstruct();
   if (n) {
     if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
       p = new event[n];
     } else {
       p = new((void*) gvp) event[n];
     }
   } else {
     if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
       p = new event;
     } else {
       p = new((void*) gvp) event;
     }
   }
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__dictEventLN_event));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__dictEvent_185_0_2(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   event* p = NULL;
   char* gvp = (char*) G__getgvp();
   //m: 1
   if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
     p = new event((int) G__int(libp->para[0]));
   } else {
     p = new((void*) gvp) event((int) G__int(libp->para[0]));
   }
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__dictEventLN_event));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__dictEvent_185_0_3(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((event*) G__getstructoffset())->SetEventNumber((int) G__int(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__dictEvent_185_0_4(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((event*) G__getstructoffset())->AddVec2d((vec2d*) G__int(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__dictEvent_185_0_5(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((event*) G__getstructoffset())->AddVec2d((double) G__double(libp->para[0]), (double) G__double(libp->para[1]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__dictEvent_185_0_6(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) ((event*) G__getstructoffset())->GetEventNumber());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__dictEvent_185_0_7(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) ((event*) G__getstructoffset())->GetNumberOfTracks());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__dictEvent_185_0_8(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 85, (long) ((event*) G__getstructoffset())->GetTrack((int) G__int(libp->para[0])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__dictEvent_185_0_9(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((event*) G__getstructoffset())->Print();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__dictEvent_185_0_10(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((event*) G__getstructoffset())->PrintTracks();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__dictEvent_185_0_11(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((event*) G__getstructoffset())->DoSort();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__dictEvent_185_0_12(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 85, (long) event::Class());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__dictEvent_185_0_13(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) event::Class_Name());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__dictEvent_185_0_14(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 115, (long) event::Class_Version());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__dictEvent_185_0_15(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      event::Dictionary();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__dictEvent_185_0_19(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((event*) G__getstructoffset())->StreamerNVirtual(*(TBuffer*) libp->para[0].ref);
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__dictEvent_185_0_20(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) event::DeclFileName());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__dictEvent_185_0_21(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) event::ImplFileLine());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__dictEvent_185_0_22(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) event::ImplFileName());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__dictEvent_185_0_23(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) event::DeclFileLine());
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic copy constructor
static int G__dictEvent_185_0_24(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)

{
   event* p;
   void* tmp = (void*) G__int(libp->para[0]);
   p = new event(*(event*) tmp);
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__dictEventLN_event));
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic destructor
typedef event G__Tevent;
static int G__dictEvent_185_0_25(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   char* gvp = (char*) G__getgvp();
   long soff = G__getstructoffset();
   int n = G__getaryconstruct();
   //
   //has_a_delete: 1
   //has_own_delete1arg: 0
   //has_own_delete2arg: 0
   //
   if (!soff) {
     return(1);
   }
   if (n) {
     if (gvp == (char*)G__PVOID) {
       delete[] (event*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       for (int i = n - 1; i >= 0; --i) {
         ((event*) (soff+(sizeof(event)*i)))->~G__Tevent();
       }
       G__setgvp((long)gvp);
     }
   } else {
     if (gvp == (char*)G__PVOID) {
       delete (event*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       ((event*) (soff))->~G__Tevent();
       G__setgvp((long)gvp);
     }
   }
   G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic assignment operator
static int G__dictEvent_185_0_26(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   event* dest = (event*) G__getstructoffset();
   *dest = *(event*) libp->para[0].ref;
   const event& obj = *dest;
   result7->ref = (long) (&obj);
   result7->obj.i = (long) (&obj);
   return(1 || funcname || hash || result7 || libp) ;
}


/* Setting up global function */

/*********************************************************
* Member function Stub
*********************************************************/

/* vec2d */

/* event */

/*********************************************************
* Global function Stub
*********************************************************/

/*********************************************************
* Get size of pointer to member function
*********************************************************/
class G__Sizep2memfuncdictEvent {
 public:
  G__Sizep2memfuncdictEvent(): p(&G__Sizep2memfuncdictEvent::sizep2memfunc) {}
    size_t sizep2memfunc() { return(sizeof(p)); }
  private:
    size_t (G__Sizep2memfuncdictEvent::*p)();
};

size_t G__get_sizep2memfuncdictEvent()
{
  G__Sizep2memfuncdictEvent a;
  G__setsizep2memfunc((int)a.sizep2memfunc());
  return((size_t)a.sizep2memfunc());
}


/*********************************************************
* virtual base class offset calculation interface
*********************************************************/

   /* Setting up class inheritance */

/*********************************************************
* Inheritance information setup/
*********************************************************/
extern "C" void G__cpp_setup_inheritancedictEvent() {

   /* Setting up class inheritance */
   if(0==G__getnumbaseclass(G__get_linked_tagnum(&G__dictEventLN_vec2d))) {
     vec2d *G__Lderived;
     G__Lderived=(vec2d*)0x1000;
     {
       TObject *G__Lpbase=(TObject*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__dictEventLN_vec2d),G__get_linked_tagnum(&G__dictEventLN_TObject),(long)G__Lpbase-(long)G__Lderived,1,1);
     }
   }
   if(0==G__getnumbaseclass(G__get_linked_tagnum(&G__dictEventLN_event))) {
     event *G__Lderived;
     G__Lderived=(event*)0x1000;
     {
       TObject *G__Lpbase=(TObject*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__dictEventLN_event),G__get_linked_tagnum(&G__dictEventLN_TObject),(long)G__Lpbase-(long)G__Lderived,1,1);
     }
   }
}

/*********************************************************
* typedef information setup/
*********************************************************/
extern "C" void G__cpp_setup_typetabledictEvent() {

   /* Setting up typedef entry */
   G__search_typename2("Version_t",115,-1,0,-1);
   G__setnewtype(-1,"Class version identifier (short)",0);
   G__search_typename2("vector<ROOT::TSchemaHelper>",117,G__get_linked_tagnum(&G__dictEventLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__dictEventLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__dictEventLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__dictEventLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__dictEventLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<TVirtualArray*>",117,G__get_linked_tagnum(&G__dictEventLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__dictEventLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__dictEventLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__dictEventLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__dictEventLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<std::bidirectional_iterator_tag,TObject*,std::ptrdiff_t,const TObject**,const TObject*&>",117,G__get_linked_tagnum(&G__dictEventLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*>",117,G__get_linked_tagnum(&G__dictEventLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*,long>",117,G__get_linked_tagnum(&G__dictEventLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*,long,const TObject**>",117,G__get_linked_tagnum(&G__dictEventLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
}

/*********************************************************
* Data Member information setup/
*********************************************************/

   /* Setting up class,struct,union tag member variable */

   /* vec2d */
static void G__setup_memvarvec2d(void) {
   G__tag_memvar_setup(G__get_linked_tagnum(&G__dictEventLN_vec2d));
   { vec2d *p; p=(vec2d*)0x1000; if (p) { }
   G__memvar_setup((void*)0,100,0,0,-1,-1,-1,2,"x=",0,(char*)NULL);
   G__memvar_setup((void*)0,100,0,0,-1,-1,-1,2,"y=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__dictEventLN_TClass),-1,-2,4,"fgIsA=",0,(char*)NULL);
   }
   G__tag_memvar_reset();
}


   /* event */
static void G__setup_memvarevent(void) {
   G__tag_memvar_setup(G__get_linked_tagnum(&G__dictEventLN_event));
   { event *p; p=(event*)0x1000; if (p) { }
   G__memvar_setup((void*)0,105,0,0,-1,-1,-1,2,"eventNumber=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__dictEventLN_TObjArray),-1,-1,2,"vec2dArray=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__dictEventLN_TClass),-1,-2,4,"fgIsA=",0,(char*)NULL);
   }
   G__tag_memvar_reset();
}

extern "C" void G__cpp_setup_memvardictEvent() {
}
/***********************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
***********************************************************/

/*********************************************************
* Member function information setup for each class
*********************************************************/
static void G__setup_memfuncvec2d(void) {
   /* vec2d */
   G__tag_memfunc_setup(G__get_linked_tagnum(&G__dictEventLN_vec2d));
   G__memfunc_setup("vec2d",468,G__dictEvent_162_0_1, 105, G__get_linked_tagnum(&G__dictEventLN_vec2d), -1, 0, 0, 1, 1, 0, "", "default", (void*) NULL, 0);
   G__memfunc_setup("vec2d",468,G__dictEvent_162_0_2, 105, G__get_linked_tagnum(&G__dictEventLN_vec2d), -1, 0, 2, 1, 1, 0, 
"d - - 0 - mx d - - 0 - my", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("operator+=",980,G__dictEvent_162_0_3, 117, G__get_linked_tagnum(&G__dictEventLN_vec2d), -1, 0, 1, 1, 1, 0, "u 'vec2d' - 1 - -", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("operator+",919,G__dictEvent_162_0_4, 117, G__get_linked_tagnum(&G__dictEventLN_vec2d), -1, 0, 1, 1, 1, 0, "u 'vec2d' - 1 - -", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("SetX",388,G__dictEvent_162_0_5, 121, -1, -1, 0, 1, 1, 1, 0, "d - - 0 - mx", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("SetY",389,G__dictEvent_162_0_6, 121, -1, -1, 0, 1, 1, 1, 0, "d - - 0 - my", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetX",376,G__dictEvent_162_0_7, 100, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetY",377,G__dictEvent_162_0_8, 100, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Print",525,G__dictEvent_162_0_9, 121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Length",610,G__dictEvent_162_0_10, 100, -1, -1, 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("IsSortable",1016,(G__InterfaceMethod) NULL,103, -1, G__defined_typename("Bool_t"), 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("Compare",711,(G__InterfaceMethod) NULL,105, -1, G__defined_typename("Int_t"), 0, 1, 1, 1, 8, "U 'TObject' - 10 - obj", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("Class",502,G__dictEvent_162_0_13, 85, G__get_linked_tagnum(&G__dictEventLN_TClass), -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (TClass* (*)())(&vec2d::Class) ), 0);
   G__memfunc_setup("Class_Name",982,G__dictEvent_162_0_14, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&vec2d::Class_Name) ), 0);
   G__memfunc_setup("Class_Version",1339,G__dictEvent_162_0_15, 115, -1, G__defined_typename("Version_t"), 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (Version_t (*)())(&vec2d::Class_Version) ), 0);
   G__memfunc_setup("Dictionary",1046,G__dictEvent_162_0_16, 121, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (void (*)())(&vec2d::Dictionary) ), 0);
   G__memfunc_setup("IsA",253,(G__InterfaceMethod) NULL,85, G__get_linked_tagnum(&G__dictEventLN_TClass), -1, 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("ShowMembers",1132,(G__InterfaceMethod) NULL,121, -1, -1, 0, 1, 1, 1, 0, "u 'TMemberInspector' - 1 - insp", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("Streamer",835,(G__InterfaceMethod) NULL,121, -1, -1, 0, 1, 1, 1, 0, "u 'TBuffer' - 1 - b", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("StreamerNVirtual",1656,G__dictEvent_162_0_20, 121, -1, -1, 0, 1, 1, 1, 0, "u 'TBuffer' - 1 - b", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("DeclFileName",1145,G__dictEvent_162_0_21, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&vec2d::DeclFileName) ), 0);
   G__memfunc_setup("ImplFileLine",1178,G__dictEvent_162_0_22, 105, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (int (*)())(&vec2d::ImplFileLine) ), 0);
   G__memfunc_setup("ImplFileName",1171,G__dictEvent_162_0_23, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&vec2d::ImplFileName) ), 0);
   G__memfunc_setup("DeclFileLine",1152,G__dictEvent_162_0_24, 105, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (int (*)())(&vec2d::DeclFileLine) ), 0);
   // automatic copy constructor
   G__memfunc_setup("vec2d", 468, G__dictEvent_162_0_25, (int) ('i'), G__get_linked_tagnum(&G__dictEventLN_vec2d), -1, 0, 1, 1, 1, 0, "u 'vec2d' - 11 - -", (char*) NULL, (void*) NULL, 0);
   // automatic destructor
   G__memfunc_setup("~vec2d", 594, G__dictEvent_162_0_26, (int) ('y'), -1, -1, 0, 0, 1, 1, 0, "", (char*) NULL, (void*) NULL, 1);
   // automatic assignment operator
   G__memfunc_setup("operator=", 937, G__dictEvent_162_0_27, (int) ('u'), G__get_linked_tagnum(&G__dictEventLN_vec2d), -1, 1, 1, 1, 1, 0, "u 'vec2d' - 11 - -", (char*) NULL, (void*) NULL, 0);
   G__tag_memfunc_reset();
}

static void G__setup_memfuncevent(void) {
   /* event */
   G__tag_memfunc_setup(G__get_linked_tagnum(&G__dictEventLN_event));
   G__memfunc_setup("event",546,G__dictEvent_185_0_1, 105, G__get_linked_tagnum(&G__dictEventLN_event), -1, 0, 0, 1, 1, 0, "", "default", (void*) NULL, 0);
   G__memfunc_setup("event",546,G__dictEvent_185_0_2, 105, G__get_linked_tagnum(&G__dictEventLN_event), -1, 0, 1, 1, 1, 0, "i - - 0 - nEv", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("SetEventNumber",1431,G__dictEvent_185_0_3, 121, -1, -1, 0, 1, 1, 1, 0, "i - - 0 - nEv", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("AddVec2d",701,G__dictEvent_185_0_4, 121, -1, -1, 0, 1, 1, 1, 0, "U 'vec2d' - 0 - mv", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("AddVec2d",701,G__dictEvent_185_0_5, 121, -1, -1, 0, 2, 1, 1, 0, 
"d - - 0 - mx d - - 0 - my", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetEventNumber",1419,G__dictEvent_185_0_6, 105, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetNumberOfTracks",1702,G__dictEvent_185_0_7, 105, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetTrack",789,G__dictEvent_185_0_8, 85, G__get_linked_tagnum(&G__dictEventLN_vec2d), -1, 0, 1, 1, 1, 0, "i - - 0 - nT", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Print",525,G__dictEvent_185_0_9, 121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("PrintTracks",1141,G__dictEvent_185_0_10, 121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("DoSort",603,G__dictEvent_185_0_11, 121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Class",502,G__dictEvent_185_0_12, 85, G__get_linked_tagnum(&G__dictEventLN_TClass), -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (TClass* (*)())(&event::Class) ), 0);
   G__memfunc_setup("Class_Name",982,G__dictEvent_185_0_13, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&event::Class_Name) ), 0);
   G__memfunc_setup("Class_Version",1339,G__dictEvent_185_0_14, 115, -1, G__defined_typename("Version_t"), 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (Version_t (*)())(&event::Class_Version) ), 0);
   G__memfunc_setup("Dictionary",1046,G__dictEvent_185_0_15, 121, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (void (*)())(&event::Dictionary) ), 0);
   G__memfunc_setup("IsA",253,(G__InterfaceMethod) NULL,85, G__get_linked_tagnum(&G__dictEventLN_TClass), -1, 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("ShowMembers",1132,(G__InterfaceMethod) NULL,121, -1, -1, 0, 1, 1, 1, 0, "u 'TMemberInspector' - 1 - insp", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("Streamer",835,(G__InterfaceMethod) NULL,121, -1, -1, 0, 1, 1, 1, 0, "u 'TBuffer' - 1 - b", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("StreamerNVirtual",1656,G__dictEvent_185_0_19, 121, -1, -1, 0, 1, 1, 1, 0, "u 'TBuffer' - 1 - b", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("DeclFileName",1145,G__dictEvent_185_0_20, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&event::DeclFileName) ), 0);
   G__memfunc_setup("ImplFileLine",1178,G__dictEvent_185_0_21, 105, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (int (*)())(&event::ImplFileLine) ), 0);
   G__memfunc_setup("ImplFileName",1171,G__dictEvent_185_0_22, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&event::ImplFileName) ), 0);
   G__memfunc_setup("DeclFileLine",1152,G__dictEvent_185_0_23, 105, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (int (*)())(&event::DeclFileLine) ), 0);
   // automatic copy constructor
   G__memfunc_setup("event", 546, G__dictEvent_185_0_24, (int) ('i'), G__get_linked_tagnum(&G__dictEventLN_event), -1, 0, 1, 1, 1, 0, "u 'event' - 11 - -", (char*) NULL, (void*) NULL, 0);
   // automatic destructor
   G__memfunc_setup("~event", 672, G__dictEvent_185_0_25, (int) ('y'), -1, -1, 0, 0, 1, 1, 0, "", (char*) NULL, (void*) NULL, 1);
   // automatic assignment operator
   G__memfunc_setup("operator=", 937, G__dictEvent_185_0_26, (int) ('u'), G__get_linked_tagnum(&G__dictEventLN_event), -1, 1, 1, 1, 1, 0, "u 'event' - 11 - -", (char*) NULL, (void*) NULL, 0);
   G__tag_memfunc_reset();
}


/*********************************************************
* Member function information setup
*********************************************************/
extern "C" void G__cpp_setup_memfuncdictEvent() {
}

/*********************************************************
* Global variable information setup for each class
*********************************************************/
static void G__cpp_setup_global0() {

   /* Setting up global variables */
   G__resetplocal();

}

static void G__cpp_setup_global1() {
}

static void G__cpp_setup_global2() {

   G__resetglobalenv();
}
extern "C" void G__cpp_setup_globaldictEvent() {
  G__cpp_setup_global0();
  G__cpp_setup_global1();
  G__cpp_setup_global2();
}

/*********************************************************
* Global function information setup for each class
*********************************************************/
static void G__cpp_setup_func0() {
   G__lastifuncposition();

}

static void G__cpp_setup_func1() {
}

static void G__cpp_setup_func2() {
}

static void G__cpp_setup_func3() {
}

static void G__cpp_setup_func4() {
}

static void G__cpp_setup_func5() {
}

static void G__cpp_setup_func6() {
}

static void G__cpp_setup_func7() {
}

static void G__cpp_setup_func8() {
}

static void G__cpp_setup_func9() {
}

static void G__cpp_setup_func10() {
}

static void G__cpp_setup_func11() {
}

static void G__cpp_setup_func12() {
}

static void G__cpp_setup_func13() {

   G__resetifuncposition();
}

extern "C" void G__cpp_setup_funcdictEvent() {
  G__cpp_setup_func0();
  G__cpp_setup_func1();
  G__cpp_setup_func2();
  G__cpp_setup_func3();
  G__cpp_setup_func4();
  G__cpp_setup_func5();
  G__cpp_setup_func6();
  G__cpp_setup_func7();
  G__cpp_setup_func8();
  G__cpp_setup_func9();
  G__cpp_setup_func10();
  G__cpp_setup_func11();
  G__cpp_setup_func12();
  G__cpp_setup_func13();
}

/*********************************************************
* Class,struct,union,enum tag information setup
*********************************************************/
/* Setup class/struct taginfo */
G__linked_taginfo G__dictEventLN_TClass = { "TClass" , 99 , -1 };
G__linked_taginfo G__dictEventLN_TBuffer = { "TBuffer" , 99 , -1 };
G__linked_taginfo G__dictEventLN_TMemberInspector = { "TMemberInspector" , 99 , -1 };
G__linked_taginfo G__dictEventLN_TObject = { "TObject" , 99 , -1 };
G__linked_taginfo G__dictEventLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR = { "vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >" , 99 , -1 };
G__linked_taginfo G__dictEventLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR = { "reverse_iterator<vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >::iterator>" , 99 , -1 };
G__linked_taginfo G__dictEventLN_TObjArray = { "TObjArray" , 99 , -1 };
G__linked_taginfo G__dictEventLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR = { "vector<TVirtualArray*,allocator<TVirtualArray*> >" , 99 , -1 };
G__linked_taginfo G__dictEventLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<TVirtualArray*,allocator<TVirtualArray*> >::iterator>" , 99 , -1 };
G__linked_taginfo G__dictEventLN_vec2d = { "vec2d" , 99 , -1 };
G__linked_taginfo G__dictEventLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR = { "iterator<bidirectional_iterator_tag,TObject*,long,const TObject**,const TObject*&>" , 115 , -1 };
G__linked_taginfo G__dictEventLN_event = { "event" , 99 , -1 };

/* Reset class/struct taginfo */
extern "C" void G__cpp_reset_tagtabledictEvent() {
  G__dictEventLN_TClass.tagnum = -1 ;
  G__dictEventLN_TBuffer.tagnum = -1 ;
  G__dictEventLN_TMemberInspector.tagnum = -1 ;
  G__dictEventLN_TObject.tagnum = -1 ;
  G__dictEventLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR.tagnum = -1 ;
  G__dictEventLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__dictEventLN_TObjArray.tagnum = -1 ;
  G__dictEventLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR.tagnum = -1 ;
  G__dictEventLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__dictEventLN_vec2d.tagnum = -1 ;
  G__dictEventLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR.tagnum = -1 ;
  G__dictEventLN_event.tagnum = -1 ;
}


extern "C" void G__cpp_setup_tagtabledictEvent() {

   /* Setting up class,struct,union tag entry */
   G__get_linked_tagnum_fwd(&G__dictEventLN_TClass);
   G__get_linked_tagnum_fwd(&G__dictEventLN_TBuffer);
   G__get_linked_tagnum_fwd(&G__dictEventLN_TMemberInspector);
   G__get_linked_tagnum_fwd(&G__dictEventLN_TObject);
   G__get_linked_tagnum_fwd(&G__dictEventLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR);
   G__get_linked_tagnum_fwd(&G__dictEventLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__dictEventLN_TObjArray);
   G__get_linked_tagnum_fwd(&G__dictEventLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR);
   G__get_linked_tagnum_fwd(&G__dictEventLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR);
   G__tagtable_setup(G__get_linked_tagnum_fwd(&G__dictEventLN_vec2d),sizeof(vec2d),-1,62720,(char*)NULL,G__setup_memvarvec2d,G__setup_memfuncvec2d);
   G__get_linked_tagnum_fwd(&G__dictEventLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR);
   G__tagtable_setup(G__get_linked_tagnum_fwd(&G__dictEventLN_event),sizeof(event),-1,62720,(char*)NULL,G__setup_memvarevent,G__setup_memfuncevent);
}
extern "C" void G__cpp_setupdictEvent(void) {
  G__check_setup_version(30051515,"G__cpp_setupdictEvent()");
  G__set_cpp_environmentdictEvent();
  G__cpp_setup_tagtabledictEvent();

  G__cpp_setup_inheritancedictEvent();

  G__cpp_setup_typetabledictEvent();

  G__cpp_setup_memvardictEvent();

  G__cpp_setup_memfuncdictEvent();
  G__cpp_setup_globaldictEvent();
  G__cpp_setup_funcdictEvent();

   if(0==G__getsizep2memfunc()) G__get_sizep2memfuncdictEvent();
  return;
}
class G__cpp_setup_initdictEvent {
  public:
    G__cpp_setup_initdictEvent() { G__add_setup_func("dictEvent",(G__incsetup)(&G__cpp_setupdictEvent)); G__call_setup_funcs(); }
   ~G__cpp_setup_initdictEvent() { G__remove_setup_func("dictEvent"); }
};
G__cpp_setup_initdictEvent G__cpp_setup_initializerdictEvent;

